### ISSUE TITLE
Links get cut at the first dash

### ISSUE THREAD

**Issue by thegcat** [jamtur01/rbot-redmine-plugin#1]
The URL glob seems to ignore dashes, at least on wiki links, but I suspect on every type of link.

Example: wiki:somepage#some-anchor gets transformed to http://someredmi.ne/wiki/someproject/somepage#some

**Comment by thegcat** [comment]
I'd say this regex: http://github.com/jamtur01/rbot-redmine-plugin/blob/master/redmine_urls.rb#L135 is to blame.

**Comment by jamtur01** [comment]
It's not there - it's the regex that pulls the Wiki URL in not the title. :)

**Comment by jamtur01** [comment]
Should be fixed in SHA: 4c539e380a80a40aeef79e5bb36de5e089844d02
