### ISSUE TITLE
Issue lookup failing

### ISSUE THREAD

**Issue by christopherkeller** [jamtur01/rbot-redmine-plugin#6]
Just updated our redmine code to the latest (Redmine 1.2.0.devel (MySQL)) and I noticed lookups failing from Rbot. 

E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:226:in `expand_reference': Error (NoMethodError) while fetching URL https://redmine/issues/show/88: undefined method`username=' for nil:NilClass
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /root/.rbot/plugins/redmine_urls.rb:248:in`page_element_contents'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /root/.rbot/plugins/redmine_urls.rb:213:in`expand_reference'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /root/.rbot/plugins/redmine_urls.rb:88:in`listen'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /root/.rbot/plugins/redmine_urls.rb:83:in`each'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /root/.rbot/plugins/redmine_urls.rb:83:in`listen'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/plugins.rb:940:in`send'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/plugins.rb:940:in`delegate'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/plugins.rb:936:in`each'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/plugins.rb:936:in`delegate'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/plugins.rb:1011:in`irc_delegate'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/ircbot.rb:671:in`initialize'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/rfc2812.rb:1509:in`call'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/rfc2812.rb:1509:in`handle'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/rfc2812.rb:1404:in`process'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/lib64/ruby/site_ruby/1.8/rbot/ircbot.rb:1000:in`mainloop'
E, [2011/07/05 14:49:12#16369] ERROR -- redmine_urls.rb:227:in `expand_reference': /usr/bin/rbot:125

**Comment by jamtur01** [comment]
Okay I don't have a 1.2.0 instance yet but I'll take a look.

**Comment by christopherkeller** [comment]
Happy to do any testing you need.

**Comment by jamtur01** [comment]
Do you know of a public instance of Redmine running 1.2.0 I can test on?

**Comment by christopherkeller** [comment]
I don't unfortunately.

**Comment by jamtur01** [comment]
We've just upgraded to 1.2.0 and I am not seeing this issue.  Are you still having problems?

**Comment by christopherkeller** [comment]
Yes, still seeing exactly the same issue. Only change was redmine updated to 1.2.

**Comment by christopherkeller** [comment]
We finally got around to checking into this and had to make one change to get it to work. 

<pre>
# diff redmine_urls.rb ~/tmp/redmine_urls.rb 
247c247
                     login = a.get(host).forms[0]

                     login = a.get(host).forms[1]
</pre>
